import type { DemoPattern, LibraryExercise } from "./types";

export const GRUPOS = [
  "Peito",
  "Costas",
  "Ombros",
  "Bíceps",
  "Tríceps",
  "Quadríceps",
  "Posterior de Coxa",
  "Glúteos",
  "Panturrilhas",
  "Abdômen",
] as const;

const seguranca = [
  "Aqueça antes de iniciar e comece com cargas leves para ajustar a técnica.",
  "Mantenha a respiração contínua e evite movimentos bruscos ou embalados.",
  "Interrompa o exercício em caso de dor, tontura ou desconforto.",
  "As informações são educativas e não substituem a orientação de um profissional de Educação Física.",
];

function ex(
  id: string,
  nome: string,
  grupo: string,
  equipamento: string,
  padrao: DemoPattern,
  finalidade: string,
  musculos: string[],
  execucao: string[],
): LibraryExercise {
  return {
    id,
    nome,
    grupo,
    equipamento,
    padrao,
    descricao: finalidade,
    info: { finalidade, musculos, execucao, seguranca },
  };
}

export const LIBRARY: LibraryExercise[] = [
  // PEITO
  ex(
    "supino-reto",
    "Supino Reto",
    "Peito",
    "Barra e banco",
    "supino",
    "Trabalhar principalmente a musculatura do peito, com participação de tríceps e ombros.",
    ["Peitoral maior", "Tríceps braquial", "Deltoide anterior"],
    [
      "Deite no banco com os pés apoiados no chão e as escápulas retraídas.",
      "Segure a barra com pegada pouco mais larga que os ombros.",
      "Desça a barra de forma controlada até a linha do peito.",
      "Empurre a carga mantendo controle, sem travar bruscamente os cotovelos.",
    ],
  ),
  ex(
    "supino-inclinado",
    "Supino Inclinado",
    "Peito",
    "Halteres ou barra",
    "supino",
    "Enfatizar a porção superior do peitoral.",
    ["Peitoral maior (porção clavicular)", "Deltoide anterior", "Tríceps"],
    [
      "Ajuste o banco entre 30° e 45°.",
      "Mantenha os punhos firmes e alinhados aos cotovelos.",
      "Desça controlando até sentir alongamento confortável.",
      "Empurre até quase a extensão dos cotovelos.",
    ],
  ),
  ex(
    "crucifixo",
    "Crucifixo",
    "Peito",
    "Halteres",
    "supino",
    "Isolar o peitoral através da adução dos braços.",
    ["Peitoral maior", "Deltoide anterior"],
    [
      "Deite no banco com halteres acima do peito e cotovelos levemente flexionados.",
      "Abra os braços em arco, controlando a descida.",
      "Feche o movimento aproximando os halteres sem batê-los.",
    ],
  ),
  ex(
    "crossover",
    "Crossover na Polia",
    "Peito",
    "Polia",
    "supino",
    "Trabalhar o peitoral com tensão constante em toda a amplitude.",
    ["Peitoral maior", "Deltoide anterior"],
    [
      "Posicione-se no centro com um pé à frente.",
      "Puxe as manoplas em arco até cruzar à frente do corpo.",
      "Retorne devagar controlando a carga.",
    ],
  ),
  ex(
    "flexao",
    "Flexão de Braço",
    "Peito",
    "Peso do corpo",
    "supino",
    "Fortalecer peito, tríceps e core usando o peso corporal.",
    ["Peitoral maior", "Tríceps", "Core"],
    [
      "Apoie as mãos pouco além da largura dos ombros.",
      "Mantenha o corpo alinhado da cabeça aos calcanhares.",
      "Desça até o peito próximo ao chão e empurre de volta.",
    ],
  ),
  // COSTAS
  ex(
    "puxada-frente",
    "Puxada Frontal",
    "Costas",
    "Polia alta",
    "puxada",
    "Desenvolver a largura das costas através da adução dos braços.",
    ["Latíssimo do dorso", "Redondo maior", "Bíceps"],
    [
      "Sente-se com as coxas presas sob o apoio.",
      "Puxe a barra até a parte alta do peito, peito aberto.",
      "Suba controlando, sem soltar a carga de uma vez.",
    ],
  ),
  ex(
    "remada-curvada",
    "Remada Curvada",
    "Costas",
    "Barra",
    "remada",
    "Desenvolver espessura das costas e a musculatura posterior.",
    ["Latíssimo do dorso", "Trapézio médio", "Romboides", "Bíceps"],
    [
      "Incline o tronco à frente mantendo a coluna neutra.",
      "Puxe a barra em direção ao abdômen.",
      "Desça controlando sem arredondar as costas.",
    ],
  ),
  ex(
    "remada-baixa",
    "Remada Baixa",
    "Costas",
    "Polia baixa",
    "remada",
    "Trabalhar as costas com apoio e menor sobrecarga lombar.",
    ["Latíssimo do dorso", "Romboides", "Trapézio médio", "Bíceps"],
    [
      "Sente-se com joelhos levemente flexionados.",
      "Puxe o triângulo até o abdômen aproximando as escápulas.",
      "Retorne controlando o movimento.",
    ],
  ),
  ex(
    "remada-unilateral",
    "Remada Unilateral (Serrote)",
    "Costas",
    "Halter e banco",
    "remada",
    "Trabalhar cada lado das costas de forma independente.",
    ["Latíssimo do dorso", "Redondo maior", "Bíceps"],
    [
      "Apoie joelho e mão no banco, coluna neutra.",
      "Puxe o halter próximo ao tronco.",
      "Desça controlando até estender o braço.",
    ],
  ),
  ex(
    "barra-fixa",
    "Barra Fixa",
    "Costas",
    "Peso do corpo",
    "puxada",
    "Fortalecer as costas usando o peso corporal.",
    ["Latíssimo do dorso", "Bíceps", "Core"],
    [
      "Segure a barra com pegada pronada.",
      "Puxe o corpo até o queixo próximo da barra.",
      "Desça controlando até quase estender os cotovelos.",
    ],
  ),
  // OMBROS
  ex(
    "desenvolvimento",
    "Desenvolvimento com Halteres",
    "Ombros",
    "Halteres",
    "desenvolvimento",
    "Trabalhar o deltoide de forma global, principalmente a porção anterior e lateral.",
    ["Deltoide anterior", "Deltoide lateral", "Tríceps"],
    [
      "Sente-se com as costas apoiadas e halteres na altura das orelhas.",
      "Empurre acima da cabeça sem travar os cotovelos.",
      "Desça controlando até a posição inicial.",
    ],
  ),
  ex(
    "elevacao-lateral",
    "Elevação Lateral",
    "Ombros",
    "Halteres",
    "elevacao",
    "Isolar a porção lateral do deltoide, responsável pela largura dos ombros.",
    ["Deltoide lateral", "Trapézio superior"],
    [
      "Em pé, mantenha cotovelos levemente flexionados.",
      "Eleve os braços até a linha dos ombros.",
      "Desça devagar sem balançar o tronco.",
    ],
  ),
  ex(
    "elevacao-frontal",
    "Elevação Frontal",
    "Ombros",
    "Halteres",
    "elevacao",
    "Enfatizar a porção anterior do deltoide.",
    ["Deltoide anterior", "Peitoral superior"],
    [
      "Segure os halteres à frente das coxas.",
      "Eleve à frente até a altura dos ombros.",
      "Retorne controlando.",
    ],
  ),
  ex(
    "crucifixo-inverso",
    "Crucifixo Inverso",
    "Ombros",
    "Halteres ou máquina",
    "elevacao",
    "Trabalhar a porção posterior do ombro e a musculatura das costas alta.",
    ["Deltoide posterior", "Trapézio médio", "Romboides"],
    [
      "Incline o tronco à frente com coluna neutra.",
      "Abra os braços lateralmente até a linha dos ombros.",
      "Retorne controlando.",
    ],
  ),
  // BÍCEPS
  ex(
    "rosca-direta",
    "Rosca Direta",
    "Bíceps",
    "Barra",
    "rosca",
    "Fortalecer o bíceps através da flexão de cotovelo.",
    ["Bíceps braquial", "Braquial", "Antebraço"],
    [
      "Em pé, segure a barra com pegada supinada.",
      "Flexione os cotovelos mantendo-os junto ao tronco.",
      "Desça controlando até estender os braços.",
    ],
  ),
  ex(
    "rosca-alternada",
    "Rosca Alternada",
    "Bíceps",
    "Halteres",
    "rosca",
    "Trabalhar o bíceps de cada braço isoladamente.",
    ["Bíceps braquial", "Braquial"],
    [
      "Segure um halter em cada mão com braços estendidos.",
      "Flexione um braço por vez girando o punho.",
      "Desça controlando e alterne.",
    ],
  ),
  ex(
    "rosca-martelo",
    "Rosca Martelo",
    "Bíceps",
    "Halteres",
    "rosca",
    "Trabalhar o bíceps e o braquiorradial com pegada neutra.",
    ["Braquiorradial", "Braquial", "Bíceps"],
    [
      "Mantenha os polegares para cima durante todo o movimento.",
      "Flexione os cotovelos sem balançar o corpo.",
      "Desça controlando.",
    ],
  ),
  ex(
    "rosca-scott",
    "Rosca Scott",
    "Bíceps",
    "Banco Scott",
    "rosca",
    "Isolar o bíceps reduzindo a participação do tronco.",
    ["Bíceps braquial", "Braquial"],
    [
      "Apoie os braços completamente no banco.",
      "Flexione os cotovelos até o topo do movimento.",
      "Desça devagar sem estender bruscamente.",
    ],
  ),
  // TRÍCEPS
  ex(
    "triceps-pulley",
    "Tríceps na Polia",
    "Tríceps",
    "Polia alta",
    "triceps",
    "Fortalecer o tríceps através da extensão de cotovelo.",
    ["Tríceps braquial (3 porções)"],
    [
      "Cotovelos junto ao tronco e tronco levemente inclinado.",
      "Estenda os cotovelos até embaixo.",
      "Retorne controlando sem abrir os cotovelos.",
    ],
  ),
  ex(
    "triceps-testa",
    "Tríceps Testa",
    "Tríceps",
    "Barra W",
    "triceps",
    "Trabalhar o tríceps com ênfase na cabeça longa.",
    ["Tríceps braquial", "Cabeça longa do tríceps"],
    [
      "Deite no banco com a barra acima da testa.",
      "Flexione os cotovelos descendo a barra controlando.",
      "Estenda os cotovelos sem afastá-los.",
    ],
  ),
  ex(
    "triceps-frances",
    "Tríceps Francês",
    "Tríceps",
    "Halter",
    "triceps",
    "Alongar e fortalecer a cabeça longa do tríceps.",
    ["Tríceps braquial"],
    [
      "Segure o halter acima da cabeça com as duas mãos.",
      "Desça atrás da cabeça controlando.",
      "Estenda os cotovelos até o topo.",
    ],
  ),
  ex(
    "mergulho",
    "Mergulho no Banco",
    "Tríceps",
    "Peso do corpo",
    "triceps",
    "Fortalecer o tríceps com o peso do corpo.",
    ["Tríceps braquial", "Deltoide anterior", "Peitoral"],
    [
      "Apoie as mãos no banco atrás do corpo.",
      "Desça flexionando os cotovelos até cerca de 90°.",
      "Empurre de volta sem forçar os ombros.",
    ],
  ),
  // QUADRÍCEPS
  ex(
    "agachamento-livre",
    "Agachamento Livre",
    "Quadríceps",
    "Barra",
    "agachamento",
    "Exercício global de pernas, com ênfase em quadríceps e glúteos.",
    ["Quadríceps", "Glúteo máximo", "Adutores", "Core"],
    [
      "Barra apoiada no trapézio, pés na largura dos ombros.",
      "Desça flexionando quadris e joelhos com coluna neutra.",
      "Suba empurrando o chão, sem deixar os joelhos colapsarem para dentro.",
    ],
  ),
  ex(
    "leg-press",
    "Leg Press",
    "Quadríceps",
    "Máquina",
    "agachamento",
    "Trabalhar pernas com apoio das costas e maior estabilidade.",
    ["Quadríceps", "Glúteo máximo", "Posterior de coxa"],
    [
      "Apoie os pés na plataforma na largura dos ombros.",
      "Desça controlando sem tirar o quadril do apoio.",
      "Empurre sem travar bruscamente os joelhos.",
    ],
  ),
  ex(
    "cadeira-extensora",
    "Cadeira Extensora",
    "Quadríceps",
    "Máquina",
    "agachamento",
    "Isolar o quadríceps.",
    ["Quadríceps"],
    [
      "Ajuste o encosto e o apoio dos tornozelos.",
      "Estenda os joelhos de forma controlada.",
      "Retorne devagar sem deixar a carga bater.",
    ],
  ),
  ex(
    "afundo",
    "Afundo / Passada",
    "Quadríceps",
    "Halteres",
    "agachamento",
    "Trabalhar pernas de forma unilateral, exigindo equilíbrio.",
    ["Quadríceps", "Glúteo máximo", "Posterior de coxa"],
    [
      "Dê um passo à frente mantendo o tronco ereto.",
      "Desça o joelho de trás em direção ao chão.",
      "Empurre com a perna da frente para voltar.",
    ],
  ),
  // POSTERIOR
  ex(
    "stiff",
    "Stiff",
    "Posterior de Coxa",
    "Barra ou halteres",
    "levantamento",
    "Trabalhar posterior de coxa e glúteos através da flexão de quadril.",
    ["Isquiotibiais", "Glúteo máximo", "Eretores da espinha"],
    [
      "Joelhos levemente flexionados, coluna neutra.",
      "Desça a barra rente às pernas empurrando o quadril para trás.",
      "Suba contraindo glúteos, sem hiperextender a lombar.",
    ],
  ),
  ex(
    "mesa-flexora",
    "Mesa Flexora",
    "Posterior de Coxa",
    "Máquina",
    "levantamento",
    "Isolar os isquiotibiais pela flexão de joelho.",
    ["Isquiotibiais", "Panturrilha (auxiliar)"],
    [
      "Deite com o rolo apoiado acima dos calcanhares.",
      "Flexione os joelhos até o limite confortável.",
      "Retorne controlando.",
    ],
  ),
  ex(
    "levantamento-terra",
    "Levantamento Terra",
    "Posterior de Coxa",
    "Barra",
    "levantamento",
    "Exercício global de cadeia posterior.",
    ["Isquiotibiais", "Glúteos", "Eretores da espinha", "Trapézio"],
    [
      "Pés sob a barra, pegada na largura dos ombros.",
      "Mantenha a coluna neutra e o peito aberto ao iniciar a subida.",
      "Estenda quadris e joelhos juntos, barra rente ao corpo.",
    ],
  ),
  // GLÚTEOS
  ex(
    "elevacao-pelvica",
    "Elevação Pélvica",
    "Glúteos",
    "Barra ou máquina",
    "gluteo",
    "Fortalecer o glúteo máximo pela extensão de quadril.",
    ["Glúteo máximo", "Isquiotibiais"],
    [
      "Apoie as escápulas no banco e a carga sobre o quadril.",
      "Eleve o quadril até alinhar tronco e coxas.",
      "Desça controlando sem apoiar totalmente.",
    ],
  ),
  ex(
    "cadeira-abdutora",
    "Cadeira Abdutora",
    "Glúteos",
    "Máquina",
    "gluteo",
    "Trabalhar glúteo médio e mínimo.",
    ["Glúteo médio", "Glúteo mínimo"],
    [
      "Sente-se com as costas apoiadas.",
      "Abra as pernas de forma controlada.",
      "Retorne devagar sem bater a carga.",
    ],
  ),
  ex(
    "coice-polia",
    "Coice na Polia",
    "Glúteos",
    "Polia baixa",
    "gluteo",
    "Isolar o glúteo máximo de forma unilateral.",
    ["Glúteo máximo", "Isquiotibiais"],
    [
      "Prenda a caneleira no tornozelo e segure o apoio.",
      "Estenda o quadril para trás sem arquear a lombar.",
      "Retorne controlando.",
    ],
  ),
  // PANTURRILHAS
  ex(
    "panturrilha-pe",
    "Panturrilha em Pé",
    "Panturrilhas",
    "Máquina ou step",
    "panturrilha",
    "Fortalecer a panturrilha com o joelho estendido.",
    ["Gastrocnêmio", "Sóleo"],
    [
      "Apoie a ponta dos pés na plataforma.",
      "Suba o máximo possível na ponta dos pés.",
      "Desça devagar até alongar a panturrilha.",
    ],
  ),
  ex(
    "panturrilha-sentado",
    "Panturrilha Sentado",
    "Panturrilhas",
    "Máquina",
    "panturrilha",
    "Enfatizar o sóleo com o joelho flexionado.",
    ["Sóleo", "Gastrocnêmio"],
    [
      "Apoie as coxas sob o suporte.",
      "Eleve os calcanhares ao máximo.",
      "Retorne controlando.",
    ],
  ),
  // ABDÔMEN
  ex(
    "abdominal-supra",
    "Abdominal Supra",
    "Abdômen",
    "Peso do corpo",
    "abdominal",
    "Trabalhar a musculatura abdominal anterior.",
    ["Reto abdominal", "Oblíquos"],
    [
      "Deite com joelhos flexionados e pés apoiados.",
      "Eleve o tronco contraindo o abdômen.",
      "Desça controlando sem puxar o pescoço.",
    ],
  ),
  ex(
    "prancha",
    "Prancha Isométrica",
    "Abdômen",
    "Peso do corpo",
    "abdominal",
    "Fortalecer o core através de contração isométrica.",
    ["Reto abdominal", "Transverso do abdômen", "Lombar"],
    [
      "Apoie antebraços e pontas dos pés.",
      "Mantenha o corpo alinhado, sem elevar ou cair o quadril.",
      "Respire normalmente durante a sustentação.",
    ],
  ),
  ex(
    "elevacao-pernas",
    "Elevação de Pernas",
    "Abdômen",
    "Peso do corpo",
    "abdominal",
    "Enfatizar a porção inferior do abdômen.",
    ["Reto abdominal inferior", "Flexores do quadril"],
    [
      "Deite com as mãos ao lado do quadril.",
      "Eleve as pernas mantendo o controle.",
      "Desça sem deixar a lombar arquear.",
    ],
  ),
];

export function findLibrary(id?: string) {
  return LIBRARY.find((e) => e.id === id);
}