/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as FichasRouteImport } from './routes/fichas'
import { Route as RapidoRouteImport } from './routes/rapido'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as FichasFichaIdRouteImport } from './routes/fichas.$fichaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasRoute = FichasRouteImport.update({
  id: '/fichas',
  path: '/fichas',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidoRoute = RapidoRouteImport.update({
  id: '/rapido',
  path: '/rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasFichaIdRoute = FichasFichaIdRouteImport.update({
  id: '/$fichaId',
  path: '/$fichaId',
  getParentRoute: () => FichasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/fichas': typeof FichasRouteWithChildren
  '/rapido': typeof RapidoRoute
  '/treino': typeof TreinoRoute
  '/fichas/$fichaId': typeof FichasFichaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/fichas': typeof FichasRouteWithChildren
  '/rapido': typeof RapidoRoute
  '/treino': typeof TreinoRoute
  '/fichas/$fichaId': typeof FichasFichaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/fichas': typeof FichasRouteWithChildren
  '/rapido': typeof RapidoRoute
  '/treino': typeof TreinoRoute
  '/fichas/$fichaId': typeof FichasFichaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/biblioteca' | '/fichas' | '/rapido' | '/treino' | '/fichas/$fichaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/biblioteca' | '/fichas' | '/rapido' | '/treino' | '/fichas/$fichaId'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/fichas'
    | '/rapido'
    | '/treino'
    | '/fichas/$fichaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  FichasRoute: typeof FichasRouteWithChildren
  RapidoRoute: typeof RapidoRoute
  TreinoRoute: typeof TreinoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas': {
      id: '/fichas'
      path: '/fichas'
      fullPath: '/fichas'
      preLoaderRoute: typeof FichasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapido': {
      id: '/rapido'
      path: '/rapido'
      fullPath: '/rapido'
      preLoaderRoute: typeof RapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas/$fichaId': {
      id: '/fichas/$fichaId'
      path: '/$fichaId'
      fullPath: '/fichas/$fichaId'
      preLoaderRoute: typeof FichasFichaIdRouteImport
      parentRoute: typeof FichasRoute
    }
  }
}

interface FichasRouteChildren {
  FichasFichaIdRoute: typeof FichasFichaIdRoute
}

const FichasRouteChildren: FichasRouteChildren = {
  FichasFichaIdRoute: FichasFichaIdRoute,
}

const FichasRouteWithChildren =
  FichasRoute._addFileChildren(FichasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  FichasRoute: FichasRouteWithChildren,
  RapidoRoute: RapidoRoute,
  TreinoRoute: TreinoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
