/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as RapidoRouteImport } from './routes/rapido'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as FichasIndexRouteImport } from './routes/fichas.index'
import { Route as FichasFichaIdRouteImport } from './routes/fichas.$fichaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidoRoute = RapidoRouteImport.update({
  id: '/rapido',
  path: '/rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FichasIndexRoute = FichasIndexRouteImport.update({
  id: '/fichas/',
  path: '/fichas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FichasFichaIdRoute = FichasFichaIdRouteImport.update({
  id: '/fichas/$fichaId',
  path: '/fichas/$fichaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/progresso': typeof ProgressoRoute
  '/rapido': typeof RapidoRoute
  '/treino': typeof TreinoRoute
  '/conta': typeof AuthenticatedContaRoute
  '/fichas/$fichaId': typeof FichasFichaIdRoute
  '/fichas/': typeof FichasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/progresso': typeof ProgressoRoute
  '/rapido': typeof RapidoRoute
  '/treino': typeof TreinoRoute
  '/conta': typeof AuthenticatedContaRoute
  '/fichas/$fichaId': typeof FichasFichaIdRoute
  '/fichas': typeof FichasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/progresso': typeof ProgressoRoute
  '/rapido': typeof RapidoRoute
  '/treino': typeof TreinoRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/fichas/$fichaId': typeof FichasFichaIdRoute
  '/fichas/': typeof FichasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/configuracoes'
    | '/historico'
    | '/progresso'
    | '/rapido'
    | '/treino'
    | '/conta'
    | '/fichas/$fichaId'
    | '/fichas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/configuracoes'
    | '/historico'
    | '/progresso'
    | '/rapido'
    | '/treino'
    | '/conta'
    | '/fichas/$fichaId'
    | '/fichas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/biblioteca'
    | '/configuracoes'
    | '/historico'
    | '/progresso'
    | '/rapido'
    | '/treino'
    | '/_authenticated/conta'
    | '/fichas/$fichaId'
    | '/fichas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  HistoricoRoute: typeof HistoricoRoute
  ProgressoRoute: typeof ProgressoRoute
  RapidoRoute: typeof RapidoRoute
  TreinoRoute: typeof TreinoRoute
  FichasFichaIdRoute: typeof FichasFichaIdRoute
  FichasIndexRoute: typeof FichasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapido': {
      id: '/rapido'
      path: '/rapido'
      fullPath: '/rapido'
      preLoaderRoute: typeof RapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/fichas/': {
      id: '/fichas/'
      path: '/fichas'
      fullPath: '/fichas/'
      preLoaderRoute: typeof FichasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fichas/$fichaId': {
      id: '/fichas/$fichaId'
      path: '/fichas/$fichaId'
      fullPath: '/fichas/$fichaId'
      preLoaderRoute: typeof FichasFichaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  HistoricoRoute: HistoricoRoute,
  ProgressoRoute: ProgressoRoute,
  RapidoRoute: RapidoRoute,
  TreinoRoute: TreinoRoute,
  FichasFichaIdRoute: FichasFichaIdRoute,
  FichasIndexRoute: FichasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
